apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-service-ingress
  namespace: catalog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "ca-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - catalog.local
    secretName: catalog-local-tls
  rules:
  - host: catalog.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catalog-service
            port:
              number: 8082

