apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: catalog
type: Opaque
stringData:
  DATABASE_URL: "postgresql://catalog_user:catalog_password@postgres-service.postgres.svc.cluster.local:5432/catalog_db"
  AUTH0_DOMAIN: "dev-bm52noc2kc3fce8w.us.auth0.com"
  AUTH0_AUDIENCE: "https://buyit.local/api"
  PAYMENTS_INTERNAL_API_TOKEN: "internal-test-token-change-in-production"
  CLOUDINARY_CLOUD_NAME: "NAME"
  CLOUDINARY_API_KEY: "API_KEY"
  CLOUDINARY_API_SECRET: "SECRET"
  # CloudFlare Images (unused - kept for future use)
  CLOUDFLARE_ACCOUNT_ID: ""
  CLOUDFLARE_API_TOKEN: ""

