apiVersion: v1
kind: Secret
metadata:
  name: cart-secrets
  namespace: cart
type: Opaque
stringData:
  DB_USERNAME: cart_user
  DB_PASSWORD: cart_password
  REDIS_HOST: redis-service.redis.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  AUTH0_DOMAIN: dev-bm52noc2kc3fce8w.us.auth0.com
  AUTH0_AUDIENCE: "https://buyit.local/api"
  PLAY_HTTP_SECRET_KEY: "6e8f1b76e3544afa9c939d01522d8628861f73a407922483244a3b1ff6a81bb66f7bb2afff5d4bb3c6a29755cca21b23b286f6629a3661059ee5018a960df7d9"
  INVENTORY_INTERNAL_API_TOKEN: "internal-test-token-change-in-production"
  ORDER_INTERNAL_API_TOKEN: "internal-test-token-change-in-production"

