apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: cart
spec:
  selector:
    app: cart-service
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
    name: http
  type: ClusterIP

