apiVersion: v1
kind: Service
metadata:
  name: admin-console
  namespace: ui
  labels:
    app: admin-console
    component: admin-console
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: admin-console

