apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-config
  namespace: payments-platform
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service.payments-platform.svc.cluster.local:5432/ledger_db
        username: ${DB_USERNAME:ledger_user}
        password: ${DB_PASSWORD:ledger_password}
    
    logging:
      level:
        com.payments.platform.ledger: INFO
        org.springframework.jdbc: WARN

