apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledger-ingress
  namespace: payments-platform
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ledger.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ledger-service
            port:
              number: 8081
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ledger-service
            port:
              number: 8081

