apiVersion: v1
kind: Secret
metadata:
  name: ledger-secrets
  namespace: payments-platform
type: Opaque
stringData:
  DB_USERNAME: ledger_user
  DB_PASSWORD: ledger_password
  INTERNAL_API_TOKEN: internal-test-token-change-in-production
  LEDGER_SERVICE_API_TOKEN: ledger-service-secret-token-change-in-production
  AUTH0_DOMAIN: dev-bm52noc2kc3fce8w.us.auth0.com
  AUTH0_AUDIENCE: "https://buyit.local/api"

