apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
stringData:
  DB_HOST: postgres-service.postgres.svc.cluster.local
  DB_NAME: auth_db
  DB_USERNAME: auth_user
  DB_PASSWORD: auth_password
  AUTH0_DOMAIN: dev-bm52noc2kc3fce8w.us.auth0.com
  AUTH0_CLIENT_ID: "aAMwHUU5cCDpgMQIkWDhmkP5ucv6lxpM"
  AUTH0_CLIENT_SECRET: "yB-CGphBFUQgTwo3YoImEGJ76Ji5VQUNlpBMJ5V2YAlIJyo5jYeCNEleJlX30v9-"
  AUTH0_REDIRECT_URI: http://auth.local/auth/callback
  AUTH0_REDIRECT_URI_PKCE: http://auth.local/auth/callback/pkce
  USER_SERVICE_URL: http://user-service.user.svc.cluster.local:9000
  JWT_SECRET_KEY: change-me-in-production-use-strong-random-key
  PLAY_HTTP_SECRET_KEY: 5aa1a7798ea0a8663a9ab0b037b753aabc070ce6fb1fbec638035bd076937dc9
