apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service
  namespace: fulfillment
spec:
  selector:
    app: fulfillment-service
  ports:
  - port: 9006
    targetPort: 9006
    protocol: TCP
    name: http
  type: ClusterIP
