apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: inventory
type: Opaque
stringData:
  DATABASE_URL: "postgresql://inventory_user:inventory_password@postgres-service.postgres.svc.cluster.local:5432/inventory_db"
  DB_USERNAME: "inventory_user"
  DB_PASSWORD: "inventory_password"
  AUTH0_DOMAIN: "dev-bm52noc2kc3fce8w.us.auth0.com"
  AUTH0_AUDIENCE: "https://buyit.local/api"
  INTERNAL_API_TOKEN: "internal-test-token-change-in-production"
  CART_SERVICE_URL: "http://cart-service.cart.svc.cluster.local:9002"
  CART_INTERNAL_API_TOKEN: "internal-test-token-change-in-production"

