apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: payments-platform
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service.postgres.svc.cluster.local:5432/payments_db
        username: ${DB_USERNAME:payments_user}
        password: ${DB_PASSWORD:payments_password}
      kafka:
        bootstrap-servers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    
    ledger:
      service:
        url: http://ledger-service.payments-platform.svc.cluster.local:8081
    
    logging:
      level:
        com.payments.platform.payments: INFO
        org.springframework.web: WARN

