apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
  namespace: payments-platform
type: Opaque
stringData:
  DB_USERNAME: payments_user
  DB_PASSWORD: payments_password
  STRIPE_SECRET_KEY: "STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "STRIPE_WEBHOOK_SECRET"