apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
  namespace: payments-platform
type: Opaque
stringData:
  DB_USERNAME: payments_user
  DB_PASSWORD: payments_password
  STRIPE_SECRET_KEY: "STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "STRIPE_WEBHOOK_SECRET"
  LEDGER_SERVICE_API_TOKEN: ledger-service-secret-token-change-in-production
  INTERNAL_API_TOKEN: internal-test-token-change-in-production
  AUTH0_DOMAIN: dev-bm52noc2kc3fce8w.us.auth0.com
  AUTH0_AUDIENCE: "https://buyit.local/api"