apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: user
type: Opaque
stringData:
  DB_USERNAME: users_user
  DB_PASSWORD: users_password
  KAFKA_BOOTSTRAP_SERVERS: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  AUTH0_DOMAIN: dev-bm52noc2kc3fce8w.us.auth0.com
  AUTH0_M2M_CLIENT_ID: "AUTH0_M2M_CLIENT_ID"
  AUTH0_M2M_CLIENT_SECRET: "AUTH0_M2M_CLIENT_SECRET"
  PLAY_HTTP_SECRET_KEY: "6e8f1b76e3544afa9c939d01522d8628861f73a407922483244a3b1ff6a81bb66f7bb2afff5d4bb3c6a29755cca21b23b286f6629a3661059ee5018a960df7d9"